import esbuild from "esbuild";
import { copyFile, rm } from "fs/promises";
import process from "process";
import builtins from "builtin-modules";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository
*/
`;

const prod = process.argv[2] === "production";

async function copyRuntimeAssets() {
  await copyFile("main.css", "styles.css").catch((error) => {
    if (error.code !== "ENOENT") {
      throw error;
    }
  });

  await rm("prebuilds", { force: true, recursive: true });
  await rm("worker", { force: true, recursive: true });
  await rm("conpty_console_list_agent.js", { force: true });
}

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "node-pty",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  plugins: [
    {
      name: "obsidian-styles",
      setup(build) {
        build.onEnd(copyRuntimeAssets);
      },
    },
  ],
});

if (prod) {
  await context.rebuild();
  await esbuild.build({
    banner: {
      js: banner,
    },
    entryPoints: ["src/helper.ts"],
    bundle: true,
    external: [
      "node-pty",
      "ws",
      ...builtins,
    ],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    outfile: "helper.js",
  });
  process.exit(0);
}

await context.watch();
